name: weather_app_dvt
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  geolocator: ^9.0.2
  http: ^0.13.5
  provider: ^6.0.3
  get_it: ^7.2.0
  shared_preferences: ^2.0.17
  intl: ^0.18.0
  connectivity_plus: ^2.3.0
  lottie: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/

  uses-material-design: true
